import { familyUsers } from "@/lib/family-users";
import type { Task } from "@/lib/types";

export { familyUsers };

export const tasks: Task[] = [
  {
    id: "english-video",
    title: "拍英语视频作业",
    note: "周一英语课前要提交。周日必须拍完，周一白天没有空。",
    createdById: "mom",
    category: "child_study",
    owners: [familyUsers[2]],
    priority: "urgent",
    taskTimeLabel: "8月10日 周一",
    taskDate: "2026-08-10",
    dueLabel: "周一课前",
    dueDate: "2026-08-10",
    remindLabel: "周日晚上",
    reminderDays: 1,
    repeatLabel: "每周一、周五课前",
    repeatWeekdays: [1, 5],
    rewardStars: 3,
    status: "todo",
    overdue: true,
    timeBucket: "overdue",
    comments: [
      {
        id: "comment-english-1",
        author: familyUsers[0],
        content: "周日晚上前拍完，别拖到周一白天。",
        createdAtLabel: "昨天 21:10"
      }
    ]
  },
  {
    id: "property-fee",
    title: "物业缴费确认",
    note: "看一下群里的缴费通知，确认金额后完成。",
    createdById: "mom",
    category: "family",
    owners: [familyUsers[0], familyUsers[1]],
    priority: "urgent",
    taskTimeLabel: "8月12日 周三",
    taskDate: "2026-08-12",
    dueLabel: "昨天 20:00",
    dueDate: "2026-08-12",
    status: "todo",
    overdue: true,
    timeBucket: "overdue",
    comments: [
      {
        id: "comment-property-1",
        author: familyUsers[1],
        content: "我下班路上看一下群消息。",
        createdAtLabel: "今天 09:18"
      }
    ]
  },
  {
    id: "reading",
    title: "晚饭后阅读 20 分钟",
    note: "小柚子自己选一本喜欢的书，读完可以讲给爸爸妈妈听。",
    createdById: "mom",
    category: "child_study",
    owners: [familyUsers[2]],
    priority: "important",
    taskTimeLabel: "8月13日 周四",
    taskDate: "2026-08-13",
    dueLabel: "8月13日 周四",
    dueDate: "2026-08-13",
    repeatLabel: "每天重复",
    repeatWeekdays: [1, 2, 3, 4, 5, 6, 7],
    rewardStars: 2,
    status: "todo",
    timeBucket: "today"
  },
  {
    id: "schoolbag",
    title: "整理书包",
    note: "检查铅笔、橡皮、水杯和明天要带的小本子。",
    createdById: "child",
    category: "child_study",
    owners: [familyUsers[2]],
    priority: "normal",
    taskTimeLabel: "8月13日 周四",
    taskDate: "2026-08-13",
    dueLabel: "8月13日 周四",
    dueDate: "2026-08-13",
    rewardStars: 1,
    status: "pending_reward",
    timeBucket: "today"
  },
  {
    id: "milk",
    title: "下班买牛奶",
    note: "买小柚子常喝的那款，如果没有就买低温鲜奶。",
    createdById: "dad",
    category: "family",
    owners: [familyUsers[1]],
    priority: "normal",
    taskTimeLabel: "8月13日 周四",
    taskDate: "2026-08-13",
    dueLabel: "8月13日 周四",
    dueDate: "2026-08-13",
    status: "todo",
    timeBucket: "today"
  },
  {
    id: "grandma-call",
    title: "给外婆回电话",
    note: "晚上吃完饭后回一下，顺便问周末要不要一起吃饭。",
    createdById: "mom",
    category: "family",
    owners: [familyUsers[0]],
    priority: "normal",
    taskTimeLabel: "8月14日 周五",
    taskDate: "2026-08-14",
    dueLabel: "8月14日 周五",
    dueDate: "2026-08-14",
    remindLabel: "提前 1 天每天提醒",
    reminderDays: 1,
    status: "todo",
    timeBucket: "tomorrow"
  },
  {
    id: "insurance",
    title: "整理保险缴费记录",
    note: "把今年已经缴过的记录拍照留存，周末前发到家庭群里。",
    createdById: "dad",
    category: "personal",
    owners: [familyUsers[1]],
    priority: "important",
    taskTimeLabel: "8月15日 周六",
    taskDate: "2026-08-15",
    dueLabel: "8月15日 周六",
    dueDate: "2026-08-15",
    remindLabel: "提前 2 天每天提醒",
    reminderDays: 2,
    status: "todo",
    timeBucket: "day_after"
  },
  {
    id: "week-cleanup",
    title: "周末收纳换季衣服",
    note: "先整理小柚子的短袖和薄外套，大人衣服只收最外层柜子。",
    createdById: "mom",
    category: "family",
    owners: [familyUsers[0], familyUsers[1]],
    priority: "normal",
    taskTimeLabel: "8月16日 周日",
    taskDate: "2026-08-16",
    dueLabel: "8月16日 周日",
    dueDate: "2026-08-16",
    repeatLabel: "每月一次",
    status: "todo",
    timeBucket: "week"
  },
  {
    id: "writing",
    title: "练字 1 页",
    note: "注意握笔姿势，慢一点没关系，写端正更重要。",
    createdById: "mom",
    category: "child_study",
    owners: [familyUsers[2]],
    priority: "important",
    taskTimeLabel: "8月13日 周四",
    taskDate: "2026-08-13",
    dueLabel: "8月13日 周四",
    dueDate: "2026-08-13",
    repeatLabel: "每天重复",
    repeatWeekdays: [1, 2, 3, 4, 5, 6, 7],
    rewardStars: 2,
    status: "todo",
    timeBucket: "today"
  },
  {
    id: "materials",
    title: "准备周五英语课材料",
    note: "把视频作业、课本和贴纸都放进书包侧袋。",
    createdById: "mom",
    category: "child_study",
    owners: [familyUsers[0], familyUsers[2]],
    priority: "important",
    taskTimeLabel: "8月14日 周五",
    taskDate: "2026-08-14",
    dueLabel: "8月14日 周五",
    dueDate: "2026-08-14",
    status: "todo",
    timeBucket: "tomorrow"
  }
];
